// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RACPD.Backend.Migrations
{
    /// <inheritdoc />
    [DbContext(typeof(RACPD.Backend.Data.AppDbContext))]
    [Migration("20260906200000_AddDesactivadoToEstadoUsuario")]
    partial class AddDesactivadoToEstadoUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.BloqueRelevo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<Guid>("PerfilDependienteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PerfilDependienteId");

                    b.ToTable("BloquesRelevo");
                });

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.BloqueTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IntervaloCupos")
                        .HasColumnType("integer");

                    b.Property<int>("PerfilDependienteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("Fecha");

                    b.ToTable("BloquesTurno");
                });

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.PerfilDependiente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("AlergiasEstructuradas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CantidadCuidadoresApoyo")
                        .HasColumnType("integer");

                    b.Property<string>("CondicionesCronicas")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FechaDesactivacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LugarNacimiento")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("MedicamentosActuales")
                        .HasColumnType("text");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NotasAdicionales")
                        .HasColumnType("text");

                    b.Property<string>("TipoSangre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VinculoPrincipalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VinculoPrincipalId");

                    b.ToTable("PerfilesDependientes");
                });

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.ReservaTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int>("BloqueTurnoId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("FechaReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("BloqueTurnoId", "UsuarioId")
                        .IsUnique()
                        .HasFilter("\"Activa\" = true");

                    b.ToTable("ReservasTurno");
                });

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("FechaCompletadoPerfil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.VinculoDependiente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PerfilDependienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("RolEnDependiente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PerfilDependienteId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId", "PerfilDependienteId")
                        .IsUnique()
                        .HasFilter("\"Activo\" = true");

                    b.ToTable("VinculosDependientes");
                });
#pragma warning restore 612, 618
        }
    }
}
