// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RACPD.Backend.Data;

#nullable disable

namespace RACPD.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910230133_HacerPerfilDependienteIdObligatorio")]
    partial class HacerPerfilDependienteIdObligatorio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.BloqueRelevo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FinUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("InicioUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PerfilDependienteId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PerfilDependienteId");

                    b.ToTable("BloquesRelevo");
                });

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.BloqueTurno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreadoPorId")
                        .HasColumnType("uuid");

                    b.Property<int>("CuposMaximos")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<int?>("IntervaloSemanas")
                        .HasColumnType("integer");

                    b.Property<Guid>("PerfilDependienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoRecurrencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("Fecha");

                    b.HasIndex("PerfilDependienteId");

                    b.ToTable("BloquesTurno");
                });

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.PerfilDependiente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("AlergiasEstructuradas")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("CondicionesCronicas")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TipoSangre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.ToTable("PerfilesDependientes");
                });

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.ReservaTurno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<Guid>("BloqueTurnoId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FechaCancelacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FechaReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("BloqueTurnoId", "UsuarioId")
                        .IsUnique()
                        .HasFilter("\"Activa\" = true");

                    b.ToTable("ReservasTurno");
                });

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FechaCompletadoPerfil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.VinculoDependiente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("AsignadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PerfilDependienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("RolEnDependiente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PerfilDependienteId")
                        .IsUnique()
                        .HasDatabaseName("IX_VinculosDependientes_UnSoloCuidadorPrincipalActivo")
                        .HasFilter("\"RolEnDependiente\" = 'CuidadorPrincipal' AND \"Activo\" = true");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId", "PerfilDependienteId")
                        .IsUnique()
                        .HasFilter("\"Activo\" = true");

                    b.ToTable("VinculosDependientes");
                });

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.BloqueRelevo", b =>
                {
                    b.HasOne("RACPD.Backend.Domain.Entities.PerfilDependiente", "PerfilDependiente")
                        .WithMany()
                        .HasForeignKey("PerfilDependienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilDependiente");
                });

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.BloqueTurno", b =>
                {
                    b.HasOne("RACPD.Backend.Domain.Entities.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RACPD.Backend.Domain.Entities.PerfilDependiente", "PerfilDependiente")
                        .WithMany()
                        .HasForeignKey("PerfilDependienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("RACPD.Backend.Domain.Entities.TareaTurnoItem", "Tareas", b1 =>
                        {
                            b1.Property<Guid>("BloqueTurnoId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Descripcion")
                                .IsRequired();

                            b1.Property<Guid>("Id");

                            b1.Property<int>("Orden");

                            b1.HasKey("BloqueTurnoId", "__synthesizedOrdinal");

                            b1.ToTable("BloquesTurno");

                            b1
                                .ToJson("Tareas")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BloqueTurnoId");
                        });

                    b.Navigation("CreadoPor");

                    b.Navigation("PerfilDependiente");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.PerfilDependiente", b =>
                {
                    b.OwnsMany("RACPD.Backend.Domain.Entities.ContactoEmergencia", "ContactosEmergencia", b1 =>
                        {
                            b1.Property<Guid>("PerfilDependienteId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Nombre")
                                .IsRequired();

                            b1.Property<string>("Relacion")
                                .IsRequired();

                            b1.Property<string>("TelefonoWhatsApp")
                                .IsRequired();

                            b1.HasKey("PerfilDependienteId", "__synthesizedOrdinal");

                            b1.ToTable("PerfilesDependientes");

                            b1
                                .ToJson("ContactosEmergencia")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PerfilDependienteId");
                        });

                    b.Navigation("ContactosEmergencia");
                });

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.ReservaTurno", b =>
                {
                    b.HasOne("RACPD.Backend.Domain.Entities.BloqueTurno", "BloqueTurno")
                        .WithMany("Reservas")
                        .HasForeignKey("BloqueTurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RACPD.Backend.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BloqueTurno");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.VinculoDependiente", b =>
                {
                    b.HasOne("RACPD.Backend.Domain.Entities.PerfilDependiente", "PerfilDependiente")
                        .WithMany()
                        .HasForeignKey("PerfilDependienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RACPD.Backend.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilDependiente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.BloqueTurno", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
