// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RACPD.Backend.Data;

#nullable disable

namespace RACPD.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901154659_AddPerfilDependienteAndBloqueRelevo")]
    partial class AddPerfilDependienteAndBloqueRelevo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.BloqueRelevo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FinUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("InicioUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PerfilDependienteId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PerfilDependienteId");

                    b.ToTable("BloquesRelevo");
                });

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.PerfilDependiente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("AlergiasEstructuradas")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("CondicionesCronicas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CuidadorPrincipalId")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoSangre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CuidadorPrincipalId");

                    b.ToTable("PerfilesDependientes");
                });

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FechaCompletadoPerfil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.BloqueRelevo", b =>
                {
                    b.HasOne("RACPD.Backend.Domain.Entities.PerfilDependiente", "PerfilDependiente")
                        .WithMany()
                        .HasForeignKey("PerfilDependienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilDependiente");
                });

            modelBuilder.Entity("RACPD.Backend.Domain.Entities.PerfilDependiente", b =>
                {
                    b.HasOne("RACPD.Backend.Domain.Entities.Usuario", "CuidadorPrincipal")
                        .WithMany()
                        .HasForeignKey("CuidadorPrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("RACPD.Backend.Domain.Entities.ContactoEmergencia", "ContactosEmergencia", b1 =>
                        {
                            b1.Property<Guid>("PerfilDependienteId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Nombre")
                                .IsRequired();

                            b1.Property<string>("Relacion")
                                .IsRequired();

                            b1.Property<string>("TelefonoWhatsApp")
                                .IsRequired();

                            b1.HasKey("PerfilDependienteId", "__synthesizedOrdinal");

                            b1.ToTable("PerfilesDependientes");

                            b1
                                .ToJson("ContactosEmergencia")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PerfilDependienteId");
                        });

                    b.Navigation("ContactosEmergencia");

                    b.Navigation("CuidadorPrincipal");
                });
#pragma warning restore 612, 618
        }
    }
}
