/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtegidasRouteImport } from './routes/_protegidas'
import { Route as InicioSesionRouteImport } from './routes/inicio-sesion'
import { Route as ProtegidasIndexRouteImport } from './routes/_protegidas/index'
import { Route as ProtegidasAgendaRouteImport } from './routes/_protegidas/agenda'
import { Route as ProtegidasFichaPacienteRouteImport } from './routes/_protegidas/ficha-paciente'

const ProtegidasRoute = ProtegidasRouteImport.update({
  id: '/_protegidas',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioSesionRoute = InicioSesionRouteImport.update({
  id: '/inicio-sesion',
  path: '/inicio-sesion',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtegidasIndexRoute = ProtegidasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtegidasRoute,
} as any)
const ProtegidasAgendaRoute = ProtegidasAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => ProtegidasRoute,
} as any)
const ProtegidasFichaPacienteRoute = ProtegidasFichaPacienteRouteImport.update({
  id: '/ficha-paciente',
  path: '/ficha-paciente',
  getParentRoute: () => ProtegidasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtegidasIndexRoute
  '/inicio-sesion': typeof InicioSesionRoute
  '/agenda': typeof ProtegidasAgendaRoute
  '/ficha-paciente': typeof ProtegidasFichaPacienteRoute
}
export interface FileRoutesByTo {
  '/inicio-sesion': typeof InicioSesionRoute
  '/agenda': typeof ProtegidasAgendaRoute
  '/ficha-paciente': typeof ProtegidasFichaPacienteRoute
  '/': typeof ProtegidasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protegidas': typeof ProtegidasRouteWithChildren
  '/inicio-sesion': typeof InicioSesionRoute
  '/_protegidas/agenda': typeof ProtegidasAgendaRoute
  '/_protegidas/ficha-paciente': typeof ProtegidasFichaPacienteRoute
  '/_protegidas/': typeof ProtegidasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inicio-sesion' | '/agenda' | '/ficha-paciente'
  fileRoutesByTo: FileRoutesByTo
  to: '/inicio-sesion' | '/agenda' | '/ficha-paciente' | '/'
  id:
    | '__root__'
    | '/_protegidas'
    | '/inicio-sesion'
    | '/_protegidas/agenda'
    | '/_protegidas/ficha-paciente'
    | '/_protegidas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtegidasRoute: typeof ProtegidasRouteWithChildren
  InicioSesionRoute: typeof InicioSesionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protegidas': {
      id: '/_protegidas'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtegidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio-sesion': {
      id: '/inicio-sesion'
      path: '/inicio-sesion'
      fullPath: '/inicio-sesion'
      preLoaderRoute: typeof InicioSesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protegidas/': {
      id: '/_protegidas/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtegidasIndexRouteImport
      parentRoute: typeof ProtegidasRoute
    }
    '/_protegidas/agenda': {
      id: '/_protegidas/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof ProtegidasAgendaRouteImport
      parentRoute: typeof ProtegidasRoute
    }
    '/_protegidas/ficha-paciente': {
      id: '/_protegidas/ficha-paciente'
      path: '/ficha-paciente'
      fullPath: '/ficha-paciente'
      preLoaderRoute: typeof ProtegidasFichaPacienteRouteImport
      parentRoute: typeof ProtegidasRoute
    }
  }
}

interface ProtegidasRouteChildren {
  ProtegidasAgendaRoute: typeof ProtegidasAgendaRoute
  ProtegidasFichaPacienteRoute: typeof ProtegidasFichaPacienteRoute
  ProtegidasIndexRoute: typeof ProtegidasIndexRoute
}

const ProtegidasRouteChildren: ProtegidasRouteChildren = {
  ProtegidasAgendaRoute: ProtegidasAgendaRoute,
  ProtegidasFichaPacienteRoute: ProtegidasFichaPacienteRoute,
  ProtegidasIndexRoute: ProtegidasIndexRoute,
}

const ProtegidasRouteWithChildren = ProtegidasRoute._addFileChildren(
  ProtegidasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtegidasRoute: ProtegidasRouteWithChildren,
  InicioSesionRoute: InicioSesionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
