/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtegidasRouteImport } from './routes/_protegidas'
import { Route as CompletarPerfilRouteImport } from './routes/completar-perfil'
import { Route as InicioSesionRouteImport } from './routes/inicio-sesion'
import { Route as ProtegidasIndexRouteImport } from './routes/_protegidas/index'
import { Route as ProtegidasAgendaRouteImport } from './routes/_protegidas/agenda'
import { Route as ProtegidasConfiguracionRouteImport } from './routes/_protegidas/configuracion'
import { Route as ProtegidasDependientesRouteImport } from './routes/_protegidas/dependientes'
import { Route as ProtegidasFichaPacienteRouteImport } from './routes/_protegidas/ficha-paciente'
import { Route as ProtegidasDependientesIndexRouteImport } from './routes/_protegidas/dependientes/index'
import { Route as ProtegidasDependientesPerfilIdRouteImport } from './routes/_protegidas/dependientes/$perfilId'
import { Route as ProtegidasDependientesNuevoRouteImport } from './routes/_protegidas/dependientes/nuevo'
import { Route as ProtegidasUsuariosInvitarRouteImport } from './routes/_protegidas/usuarios/invitar'
import { Route as ProtegidasDependientesPerfilIdAccesoRouteImport } from './routes/_protegidas/dependientes/$perfilId_.acceso'

const ProtegidasRoute = ProtegidasRouteImport.update({
  id: '/_protegidas',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletarPerfilRoute = CompletarPerfilRouteImport.update({
  id: '/completar-perfil',
  path: '/completar-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioSesionRoute = InicioSesionRouteImport.update({
  id: '/inicio-sesion',
  path: '/inicio-sesion',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtegidasIndexRoute = ProtegidasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtegidasRoute,
} as any)
const ProtegidasAgendaRoute = ProtegidasAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => ProtegidasRoute,
} as any)
const ProtegidasConfiguracionRoute = ProtegidasConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => ProtegidasRoute,
} as any)
const ProtegidasDependientesRoute = ProtegidasDependientesRouteImport.update({
  id: '/dependientes',
  path: '/dependientes',
  getParentRoute: () => ProtegidasRoute,
} as any)
const ProtegidasFichaPacienteRoute = ProtegidasFichaPacienteRouteImport.update({
  id: '/ficha-paciente',
  path: '/ficha-paciente',
  getParentRoute: () => ProtegidasRoute,
} as any)
const ProtegidasDependientesIndexRoute =
  ProtegidasDependientesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtegidasDependientesRoute,
  } as any)
const ProtegidasDependientesPerfilIdRoute =
  ProtegidasDependientesPerfilIdRouteImport.update({
    id: '/$perfilId',
    path: '/$perfilId',
    getParentRoute: () => ProtegidasDependientesRoute,
  } as any)
const ProtegidasDependientesNuevoRoute =
  ProtegidasDependientesNuevoRouteImport.update({
    id: '/nuevo',
    path: '/nuevo',
    getParentRoute: () => ProtegidasDependientesRoute,
  } as any)
const ProtegidasUsuariosInvitarRoute =
  ProtegidasUsuariosInvitarRouteImport.update({
    id: '/usuarios/invitar',
    path: '/usuarios/invitar',
    getParentRoute: () => ProtegidasRoute,
  } as any)
const ProtegidasDependientesPerfilIdAccesoRoute =
  ProtegidasDependientesPerfilIdAccesoRouteImport.update({
    id: '/$perfilId_/acceso',
    path: '/$perfilId/acceso',
    getParentRoute: () => ProtegidasDependientesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtegidasIndexRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/inicio-sesion': typeof InicioSesionRoute
  '/agenda': typeof ProtegidasAgendaRoute
  '/configuracion': typeof ProtegidasConfiguracionRoute
  '/dependientes': typeof ProtegidasDependientesRouteWithChildren
  '/ficha-paciente': typeof ProtegidasFichaPacienteRoute
  '/dependientes/$perfilId': typeof ProtegidasDependientesPerfilIdRoute
  '/dependientes/nuevo': typeof ProtegidasDependientesNuevoRoute
  '/usuarios/invitar': typeof ProtegidasUsuariosInvitarRoute
  '/dependientes/': typeof ProtegidasDependientesIndexRoute
  '/dependientes/$perfilId/acceso': typeof ProtegidasDependientesPerfilIdAccesoRoute
}
export interface FileRoutesByTo {
  '/completar-perfil': typeof CompletarPerfilRoute
  '/inicio-sesion': typeof InicioSesionRoute
  '/agenda': typeof ProtegidasAgendaRoute
  '/configuracion': typeof ProtegidasConfiguracionRoute
  '/ficha-paciente': typeof ProtegidasFichaPacienteRoute
  '/': typeof ProtegidasIndexRoute
  '/dependientes/$perfilId': typeof ProtegidasDependientesPerfilIdRoute
  '/dependientes/nuevo': typeof ProtegidasDependientesNuevoRoute
  '/usuarios/invitar': typeof ProtegidasUsuariosInvitarRoute
  '/dependientes': typeof ProtegidasDependientesIndexRoute
  '/dependientes/$perfilId/acceso': typeof ProtegidasDependientesPerfilIdAccesoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protegidas': typeof ProtegidasRouteWithChildren
  '/completar-perfil': typeof CompletarPerfilRoute
  '/inicio-sesion': typeof InicioSesionRoute
  '/_protegidas/agenda': typeof ProtegidasAgendaRoute
  '/_protegidas/configuracion': typeof ProtegidasConfiguracionRoute
  '/_protegidas/dependientes': typeof ProtegidasDependientesRouteWithChildren
  '/_protegidas/ficha-paciente': typeof ProtegidasFichaPacienteRoute
  '/_protegidas/': typeof ProtegidasIndexRoute
  '/_protegidas/dependientes/$perfilId': typeof ProtegidasDependientesPerfilIdRoute
  '/_protegidas/dependientes/nuevo': typeof ProtegidasDependientesNuevoRoute
  '/_protegidas/usuarios/invitar': typeof ProtegidasUsuariosInvitarRoute
  '/_protegidas/dependientes/': typeof ProtegidasDependientesIndexRoute
  '/_protegidas/dependientes/$perfilId_/acceso': typeof ProtegidasDependientesPerfilIdAccesoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/completar-perfil'
    | '/inicio-sesion'
    | '/agenda'
    | '/configuracion'
    | '/dependientes'
    | '/ficha-paciente'
    | '/dependientes/$perfilId'
    | '/dependientes/nuevo'
    | '/usuarios/invitar'
    | '/dependientes/'
    | '/dependientes/$perfilId/acceso'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/completar-perfil'
    | '/inicio-sesion'
    | '/agenda'
    | '/configuracion'
    | '/ficha-paciente'
    | '/'
    | '/dependientes/$perfilId'
    | '/dependientes/nuevo'
    | '/usuarios/invitar'
    | '/dependientes'
    | '/dependientes/$perfilId/acceso'
  id:
    | '__root__'
    | '/_protegidas'
    | '/completar-perfil'
    | '/inicio-sesion'
    | '/_protegidas/agenda'
    | '/_protegidas/configuracion'
    | '/_protegidas/dependientes'
    | '/_protegidas/ficha-paciente'
    | '/_protegidas/'
    | '/_protegidas/dependientes/$perfilId'
    | '/_protegidas/dependientes/nuevo'
    | '/_protegidas/usuarios/invitar'
    | '/_protegidas/dependientes/'
    | '/_protegidas/dependientes/$perfilId_/acceso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtegidasRoute: typeof ProtegidasRouteWithChildren
  CompletarPerfilRoute: typeof CompletarPerfilRoute
  InicioSesionRoute: typeof InicioSesionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protegidas': {
      id: '/_protegidas'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtegidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completar-perfil': {
      id: '/completar-perfil'
      path: '/completar-perfil'
      fullPath: '/completar-perfil'
      preLoaderRoute: typeof CompletarPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio-sesion': {
      id: '/inicio-sesion'
      path: '/inicio-sesion'
      fullPath: '/inicio-sesion'
      preLoaderRoute: typeof InicioSesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protegidas/': {
      id: '/_protegidas/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtegidasIndexRouteImport
      parentRoute: typeof ProtegidasRoute
    }
    '/_protegidas/agenda': {
      id: '/_protegidas/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof ProtegidasAgendaRouteImport
      parentRoute: typeof ProtegidasRoute
    }
    '/_protegidas/configuracion': {
      id: '/_protegidas/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ProtegidasConfiguracionRouteImport
      parentRoute: typeof ProtegidasRoute
    }
    '/_protegidas/dependientes': {
      id: '/_protegidas/dependientes'
      path: '/dependientes'
      fullPath: '/dependientes'
      preLoaderRoute: typeof ProtegidasDependientesRouteImport
      parentRoute: typeof ProtegidasRoute
    }
    '/_protegidas/ficha-paciente': {
      id: '/_protegidas/ficha-paciente'
      path: '/ficha-paciente'
      fullPath: '/ficha-paciente'
      preLoaderRoute: typeof ProtegidasFichaPacienteRouteImport
      parentRoute: typeof ProtegidasRoute
    }
    '/_protegidas/dependientes/': {
      id: '/_protegidas/dependientes/'
      path: '/'
      fullPath: '/dependientes/'
      preLoaderRoute: typeof ProtegidasDependientesIndexRouteImport
      parentRoute: typeof ProtegidasDependientesRoute
    }
    '/_protegidas/dependientes/$perfilId': {
      id: '/_protegidas/dependientes/$perfilId'
      path: '/$perfilId'
      fullPath: '/dependientes/$perfilId'
      preLoaderRoute: typeof ProtegidasDependientesPerfilIdRouteImport
      parentRoute: typeof ProtegidasDependientesRoute
    }
    '/_protegidas/dependientes/nuevo': {
      id: '/_protegidas/dependientes/nuevo'
      path: '/nuevo'
      fullPath: '/dependientes/nuevo'
      preLoaderRoute: typeof ProtegidasDependientesNuevoRouteImport
      parentRoute: typeof ProtegidasDependientesRoute
    }
    '/_protegidas/usuarios/invitar': {
      id: '/_protegidas/usuarios/invitar'
      path: '/usuarios/invitar'
      fullPath: '/usuarios/invitar'
      preLoaderRoute: typeof ProtegidasUsuariosInvitarRouteImport
      parentRoute: typeof ProtegidasRoute
    }
    '/_protegidas/dependientes/$perfilId_/acceso': {
      id: '/_protegidas/dependientes/$perfilId_/acceso'
      path: '/$perfilId/acceso'
      fullPath: '/dependientes/$perfilId/acceso'
      preLoaderRoute: typeof ProtegidasDependientesPerfilIdAccesoRouteImport
      parentRoute: typeof ProtegidasDependientesRoute
    }
  }
}

interface ProtegidasDependientesRouteChildren {
  ProtegidasDependientesPerfilIdRoute: typeof ProtegidasDependientesPerfilIdRoute
  ProtegidasDependientesNuevoRoute: typeof ProtegidasDependientesNuevoRoute
  ProtegidasDependientesIndexRoute: typeof ProtegidasDependientesIndexRoute
  ProtegidasDependientesPerfilIdAccesoRoute: typeof ProtegidasDependientesPerfilIdAccesoRoute
}

const ProtegidasDependientesRouteChildren: ProtegidasDependientesRouteChildren =
  {
    ProtegidasDependientesPerfilIdRoute: ProtegidasDependientesPerfilIdRoute,
    ProtegidasDependientesNuevoRoute: ProtegidasDependientesNuevoRoute,
    ProtegidasDependientesIndexRoute: ProtegidasDependientesIndexRoute,
    ProtegidasDependientesPerfilIdAccesoRoute:
      ProtegidasDependientesPerfilIdAccesoRoute,
  }

const ProtegidasDependientesRouteWithChildren =
  ProtegidasDependientesRoute._addFileChildren(
    ProtegidasDependientesRouteChildren,
  )

interface ProtegidasRouteChildren {
  ProtegidasAgendaRoute: typeof ProtegidasAgendaRoute
  ProtegidasConfiguracionRoute: typeof ProtegidasConfiguracionRoute
  ProtegidasDependientesRoute: typeof ProtegidasDependientesRouteWithChildren
  ProtegidasFichaPacienteRoute: typeof ProtegidasFichaPacienteRoute
  ProtegidasIndexRoute: typeof ProtegidasIndexRoute
  ProtegidasUsuariosInvitarRoute: typeof ProtegidasUsuariosInvitarRoute
}

const ProtegidasRouteChildren: ProtegidasRouteChildren = {
  ProtegidasAgendaRoute: ProtegidasAgendaRoute,
  ProtegidasConfiguracionRoute: ProtegidasConfiguracionRoute,
  ProtegidasDependientesRoute: ProtegidasDependientesRouteWithChildren,
  ProtegidasFichaPacienteRoute: ProtegidasFichaPacienteRoute,
  ProtegidasIndexRoute: ProtegidasIndexRoute,
  ProtegidasUsuariosInvitarRoute: ProtegidasUsuariosInvitarRoute,
}

const ProtegidasRouteWithChildren = ProtegidasRoute._addFileChildren(
  ProtegidasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtegidasRoute: ProtegidasRouteWithChildren,
  CompletarPerfilRoute: CompletarPerfilRoute,
  InicioSesionRoute: InicioSesionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
