/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtegidasRouteImport } from './routes/_protegidas'
import { Route as InicioSesionRouteImport } from './routes/inicio-sesion'
import { Route as ProtegidasIndexRouteImport } from './routes/_protegidas/index'
import { Route as ProtegidasAgendaRouteImport } from './routes/_protegidas/agenda'
import { Route as ProtegidasCompletarPerfilRouteImport } from './routes/_protegidas/completar-perfil'
import { Route as ProtegidasConfiguracionRouteImport } from './routes/_protegidas/configuracion'
import { Route as ProtegidasFichaPacienteRouteImport } from './routes/_protegidas/ficha-paciente'
import { Route as ProtegidasPerfilDependienteRouteImport } from './routes/_protegidas/perfil-dependiente'
import { Route as ProtegidasPerfilDependienteSosRouteImport } from './routes/_protegidas/perfil-dependiente/sos'
import { Route as ProtegidasUsuariosInvitarRouteImport } from './routes/_protegidas/usuarios/invitar'

const ProtegidasRoute = ProtegidasRouteImport.update({
  id: '/_protegidas',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioSesionRoute = InicioSesionRouteImport.update({
  id: '/inicio-sesion',
  path: '/inicio-sesion',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtegidasIndexRoute = ProtegidasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtegidasRoute,
} as any)
const ProtegidasAgendaRoute = ProtegidasAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => ProtegidasRoute,
} as any)
const ProtegidasCompletarPerfilRoute =
  ProtegidasCompletarPerfilRouteImport.update({
    id: '/completar-perfil',
    path: '/completar-perfil',
    getParentRoute: () => ProtegidasRoute,
  } as any)
const ProtegidasConfiguracionRoute = ProtegidasConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => ProtegidasRoute,
} as any)
const ProtegidasFichaPacienteRoute = ProtegidasFichaPacienteRouteImport.update({
  id: '/ficha-paciente',
  path: '/ficha-paciente',
  getParentRoute: () => ProtegidasRoute,
} as any)
const ProtegidasPerfilDependienteRoute =
  ProtegidasPerfilDependienteRouteImport.update({
    id: '/perfil-dependiente',
    path: '/perfil-dependiente',
    getParentRoute: () => ProtegidasRoute,
  } as any)
const ProtegidasPerfilDependienteSosRoute =
  ProtegidasPerfilDependienteSosRouteImport.update({
    id: '/sos',
    path: '/sos',
    getParentRoute: () => ProtegidasPerfilDependienteRoute,
  } as any)
const ProtegidasUsuariosInvitarRoute =
  ProtegidasUsuariosInvitarRouteImport.update({
    id: '/usuarios/invitar',
    path: '/usuarios/invitar',
    getParentRoute: () => ProtegidasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtegidasIndexRoute
  '/inicio-sesion': typeof InicioSesionRoute
  '/agenda': typeof ProtegidasAgendaRoute
  '/completar-perfil': typeof ProtegidasCompletarPerfilRoute
  '/configuracion': typeof ProtegidasConfiguracionRoute
  '/ficha-paciente': typeof ProtegidasFichaPacienteRoute
  '/perfil-dependiente': typeof ProtegidasPerfilDependienteRouteWithChildren
  '/perfil-dependiente/sos': typeof ProtegidasPerfilDependienteSosRoute
  '/usuarios/invitar': typeof ProtegidasUsuariosInvitarRoute
}
export interface FileRoutesByTo {
  '/inicio-sesion': typeof InicioSesionRoute
  '/agenda': typeof ProtegidasAgendaRoute
  '/completar-perfil': typeof ProtegidasCompletarPerfilRoute
  '/configuracion': typeof ProtegidasConfiguracionRoute
  '/ficha-paciente': typeof ProtegidasFichaPacienteRoute
  '/perfil-dependiente': typeof ProtegidasPerfilDependienteRouteWithChildren
  '/': typeof ProtegidasIndexRoute
  '/perfil-dependiente/sos': typeof ProtegidasPerfilDependienteSosRoute
  '/usuarios/invitar': typeof ProtegidasUsuariosInvitarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protegidas': typeof ProtegidasRouteWithChildren
  '/inicio-sesion': typeof InicioSesionRoute
  '/_protegidas/agenda': typeof ProtegidasAgendaRoute
  '/_protegidas/completar-perfil': typeof ProtegidasCompletarPerfilRoute
  '/_protegidas/configuracion': typeof ProtegidasConfiguracionRoute
  '/_protegidas/ficha-paciente': typeof ProtegidasFichaPacienteRoute
  '/_protegidas/perfil-dependiente': typeof ProtegidasPerfilDependienteRouteWithChildren
  '/_protegidas/': typeof ProtegidasIndexRoute
  '/_protegidas/perfil-dependiente/sos': typeof ProtegidasPerfilDependienteSosRoute
  '/_protegidas/usuarios/invitar': typeof ProtegidasUsuariosInvitarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inicio-sesion'
    | '/agenda'
    | '/completar-perfil'
    | '/configuracion'
    | '/ficha-paciente'
    | '/perfil-dependiente'
    | '/perfil-dependiente/sos'
    | '/usuarios/invitar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/inicio-sesion'
    | '/agenda'
    | '/completar-perfil'
    | '/configuracion'
    | '/ficha-paciente'
    | '/perfil-dependiente'
    | '/'
    | '/perfil-dependiente/sos'
    | '/usuarios/invitar'
  id:
    | '__root__'
    | '/_protegidas'
    | '/inicio-sesion'
    | '/_protegidas/agenda'
    | '/_protegidas/completar-perfil'
    | '/_protegidas/configuracion'
    | '/_protegidas/ficha-paciente'
    | '/_protegidas/perfil-dependiente'
    | '/_protegidas/'
    | '/_protegidas/perfil-dependiente/sos'
    | '/_protegidas/usuarios/invitar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtegidasRoute: typeof ProtegidasRouteWithChildren
  InicioSesionRoute: typeof InicioSesionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protegidas': {
      id: '/_protegidas'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtegidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio-sesion': {
      id: '/inicio-sesion'
      path: '/inicio-sesion'
      fullPath: '/inicio-sesion'
      preLoaderRoute: typeof InicioSesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protegidas/': {
      id: '/_protegidas/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtegidasIndexRouteImport
      parentRoute: typeof ProtegidasRoute
    }
    '/_protegidas/agenda': {
      id: '/_protegidas/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof ProtegidasAgendaRouteImport
      parentRoute: typeof ProtegidasRoute
    }
    '/_protegidas/completar-perfil': {
      id: '/_protegidas/completar-perfil'
      path: '/completar-perfil'
      fullPath: '/completar-perfil'
      preLoaderRoute: typeof ProtegidasCompletarPerfilRouteImport
      parentRoute: typeof ProtegidasRoute
    }
    '/_protegidas/configuracion': {
      id: '/_protegidas/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ProtegidasConfiguracionRouteImport
      parentRoute: typeof ProtegidasRoute
    }
    '/_protegidas/ficha-paciente': {
      id: '/_protegidas/ficha-paciente'
      path: '/ficha-paciente'
      fullPath: '/ficha-paciente'
      preLoaderRoute: typeof ProtegidasFichaPacienteRouteImport
      parentRoute: typeof ProtegidasRoute
    }
    '/_protegidas/perfil-dependiente': {
      id: '/_protegidas/perfil-dependiente'
      path: '/perfil-dependiente'
      fullPath: '/perfil-dependiente'
      preLoaderRoute: typeof ProtegidasPerfilDependienteRouteImport
      parentRoute: typeof ProtegidasRoute
    }
    '/_protegidas/perfil-dependiente/sos': {
      id: '/_protegidas/perfil-dependiente/sos'
      path: '/sos'
      fullPath: '/perfil-dependiente/sos'
      preLoaderRoute: typeof ProtegidasPerfilDependienteSosRouteImport
      parentRoute: typeof ProtegidasPerfilDependienteRoute
    }
    '/_protegidas/usuarios/invitar': {
      id: '/_protegidas/usuarios/invitar'
      path: '/usuarios/invitar'
      fullPath: '/usuarios/invitar'
      preLoaderRoute: typeof ProtegidasUsuariosInvitarRouteImport
      parentRoute: typeof ProtegidasRoute
    }
  }
}

interface ProtegidasPerfilDependienteRouteChildren {
  ProtegidasPerfilDependienteSosRoute: typeof ProtegidasPerfilDependienteSosRoute
}

const ProtegidasPerfilDependienteRouteChildren: ProtegidasPerfilDependienteRouteChildren =
  {
    ProtegidasPerfilDependienteSosRoute: ProtegidasPerfilDependienteSosRoute,
  }

const ProtegidasPerfilDependienteRouteWithChildren =
  ProtegidasPerfilDependienteRoute._addFileChildren(
    ProtegidasPerfilDependienteRouteChildren,
  )

interface ProtegidasRouteChildren {
  ProtegidasAgendaRoute: typeof ProtegidasAgendaRoute
  ProtegidasCompletarPerfilRoute: typeof ProtegidasCompletarPerfilRoute
  ProtegidasConfiguracionRoute: typeof ProtegidasConfiguracionRoute
  ProtegidasFichaPacienteRoute: typeof ProtegidasFichaPacienteRoute
  ProtegidasPerfilDependienteRoute: typeof ProtegidasPerfilDependienteRouteWithChildren
  ProtegidasIndexRoute: typeof ProtegidasIndexRoute
  ProtegidasUsuariosInvitarRoute: typeof ProtegidasUsuariosInvitarRoute
}

const ProtegidasRouteChildren: ProtegidasRouteChildren = {
  ProtegidasAgendaRoute: ProtegidasAgendaRoute,
  ProtegidasCompletarPerfilRoute: ProtegidasCompletarPerfilRoute,
  ProtegidasConfiguracionRoute: ProtegidasConfiguracionRoute,
  ProtegidasFichaPacienteRoute: ProtegidasFichaPacienteRoute,
  ProtegidasPerfilDependienteRoute:
    ProtegidasPerfilDependienteRouteWithChildren,
  ProtegidasIndexRoute: ProtegidasIndexRoute,
  ProtegidasUsuariosInvitarRoute: ProtegidasUsuariosInvitarRoute,
}

const ProtegidasRouteWithChildren = ProtegidasRoute._addFileChildren(
  ProtegidasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtegidasRoute: ProtegidasRouteWithChildren,
  InicioSesionRoute: InicioSesionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
